### ISSUE TITLE
Make excludeEnd on DemandTimePeriodService modifiable

### ISSUE THREAD

**Issue by atchapcyp** [energywebfoundation/origin#1341]
https://github.com/energywebfoundation/origin/blob/e24268d9dbadf0aa070cceb8efdcb54da9e23b5f/packages/exchange/src/pods/demand/demand-time-period.service.ts#L21

Currently, If a user wants to create a monthly demand of 2 months user needs to input Jan, 1 - March, 1. Which is not a good experience when frontend app uses a month-picker component (user need to click on Jan, Feb, and March).

I think it will be better if we allow the service caller decide how to adjust the demand period (frontend friendly).

**Comment by kosecki123** [comment]
Fixed in #1342
