### ISSUE TITLE
yarn run:demo - Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by asautins** [energywebfoundation/origin#157]
I am following the instructions on https://github.com/energywebfoundation/origin/wiki/Origin-Deployment.  When I get to step #2 "Demo - contracts deployment" and execute "yarn run:demo" I get the following error:

@energyweb/utils-demo: (node:16835) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""

My .env is the .env.example minus the optional section.

**Comment by josipbagaric** [comment]
Hi @asautins, what is the `WEB3` variable set to in your `.env`?

**Comment by asautins** [comment]
The following are my URL settings in .env.  Taken directly from .env.example.

MODE="production"
WEB3="http://localhost:8545"
BACKEND_URL="http://localhost:3030"
UI_BASE_URL="http://localhost:3000"
ENERGY_API_BASE_URL="http://localhost:3031"

**Comment by josipbagaric** [comment]
Thanks @asautins, could you send the log? Starting from `yarn run:demo` onwards. Thank you!

**Comment by tkarpeichik** [comment]
Here's the trace:

yarn run:demo
yarn run v1.19.1
$ lerna run start --scope @energyweb/utils-demo --stream
lerna notice cli v3.18.1
lerna info versioning independent
lerna notice filter including "@energyweb/utils-demo"
lerna info filter [ '@energyweb/utils-demo' ]
lerna info Executing command in 1 package: "yarn run start"
@energyweb/utils-demo: $ ts-node src/deploy
@energyweb/utils-demo: -----------------------------------------------------------
@energyweb/utils-demo: (node:643) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
@energyweb/utils-demo:     at Object.InvalidResponse (/Users/tkarpeichik/repos/origin/ewf-monorepo/node_modules/web3-core-helpers/src/errors.js:42:16)
@energyweb/utils-demo:     at XMLHttpRequest.request.onreadystatechange (/Users/tkarpeichik/repos/origin/ewf-monorepo/node_modules/web3-providers-http/src/index.js:92:32)
@energyweb/utils-demo:     at XMLHttpRequestEventTarget.dispatchEvent (/Users/tkarpeichik/repos/origin/ewf-monorepo/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
@energyweb/utils-demo:     at XMLHttpRequest._setReadyState (/Users/tkarpeichik/repos/origin/ewf-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
@energyweb/utils-demo:     at XMLHttpRequest._onHttpRequestError (/Users/tkarpeichik/repos/origin/ewf-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
@energyweb/utils-demo:     at ClientRequest.<anonymous> (/Users/tkarpeichik/repos/origin/ewf-monorepo/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
@energyweb/utils-demo:     at ClientRequest.emit (events.js:198:13)
@energyweb/utils-demo:     at ClientRequest.EventEmitter.emit (domain.js:448:20)
@energyweb/utils-demo:     at Socket.socketErrorListener (_http_client.js:392:9)
@energyweb/utils-demo:     at Socket.emit (events.js:198:13)
@energyweb/utils-demo:     at Socket.EventEmitter.emit (domain.js:448:20)
@energyweb/utils-demo:     at emitErrorNT (internal/streams/destroy.js:91:8)
@energyweb/utils-demo:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
@energyweb/utils-demo:     at process._tickCallback (internal/process/next_tick.js:63:19)
@energyweb/utils-demo: (node:643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
@energyweb/utils-demo: (node:643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lerna success run Ran npm script 'start' in 1 package in 8.6s:
lerna success - @energyweb/utils-demo
✨  Done in 8.95s.

**Comment by e00dan** [comment]
Hello @asautins, @tkarpeichik,

Seems that first you need to start local Ganache instance:

```
yarn run:ganache
```

before you use:

```
yarn run:demo
```

Above information was missing from the wiki, therefore I updated it (thanks!). Here's link to that section:
https://github.com/energywebfoundation/origin/wiki/Origin-Deployment#1-blockchain-aka-web3-rpc

**Comment by asautins** [comment]
Thank you.  That resolves this issue.
