### ISSUE TITLE
Coin integration

### ISSUE THREAD

**Issue by AnasSaeed123** [energywebfoundation/origin#1632]
Is there any js-sdk of energy web token for transaction available?

I want to integrate coin in OPOLO hardware wallet.

**Comment by revipalevi** [comment]
How to get?

**Comment by josipbagaric** [comment]
The Origin SDK has nothing to do with the Energy Web Token (EWT). Closing the issue as unrelated to this repo.

**Comment by josipbagaric** [comment]
For running transactions on the Energy Web Chain, you can use https://wallet.energyweb.org.

If you want to run transactions from code, you can use Ethers.js or Web3.js with our EWC and Volta RPC nodes.

**Comment by AnasSaeed123** [comment]
I am searching for js-sdk for the integration of energy webtoken in
hardware wallet?

Is there any discord channel available for developers?
