### ISSUE TITLE
Gas price calculation rounding error

### ISSUE THREAD

**Issue by Agupane** [energywebfoundation/origin#1648]
## Description

- When calculating the gas price, the service results always 0 for `slow`, `standard` and `fast`. It seems that there's a problem when rounding a very small value [here](https://github.com/energywebfoundation/gasprice/blob/master/gas_price.py#L76).

This is the current return of the station:

```
{
"health": true,
"block_number": 8532236,
"block_time": 5.176,
"slow": 0,
"standard": 0,
"fast": 0,
"instant": 97
}
```

Note: Tried to open the issue on [gas price repo](https://github.com/energywebfoundation/gasprice) but seems that the issues sections is not active there so I created it here

**Comment by kosecki123** [comment]
Not sure about how this is related to Origin. Closing.
