### ISSUE TITLE
Unable to connect to the database.

### ISSUE THREAD

**Issue by tttbone8122** [energywebfoundation/origin#1858]
After typing `yarn build` I get the following error:

```
 [Nest] 44818   - 01/04/2021, 2:00:04 PM   [ExceptionHandler] Unable to connect to the database. Retrying (1)...
@energyweb/origin-organization-irec-api-client: error: password authentication failed for user "postgres"
```

Yarn version: 1.22.5
Psql version: (PostgreSQL) 12.5

I followed the guide [(Run Demo)](https://github.com/energywebfoundation/origin)

Maybe I did something wrong with the `.env.example` file (?)

**Comment by kosecki123** [comment]
Default credentials for Postgres SQL are set to user: `postgres` password: `postgres` which means if you did setup using our guide you don't need to put them into `.env` file. For test rename `.env.example` to `.env` and see if that helped.
