### ISSUE TITLE
node-pre-gyp ERR error

### ISSUE THREAD

**Issue by roockiee** [energywebfoundation/origin#2111]
In the new version with node 14.0.0 I am getting the following error after typing yarn:

    node-pre-gyp ERR! cwd /home/origin/node_modules/sqlite3
    node-pre-gyp ERR! node -v v14.0.0
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok 

I had to update some things in the code and change the node to version 14.x.x After that I got an error

First, I tried:

```
rm yarn.lock && yarn

yarn upgrade
```

I've cleared the cache and the error still occur (yarn cache clean)

Also tried in this order:

```
    rm yarn.lock
    yarn cache clean
    yarn
```

I think that my version of the grpc library is old and is not compatible with that version of Node, so I tried:

    npm install grpc --build-from-source

I will add that the older version works fine. 
How can I solve it?

**Comment by kosecki123** [comment]
Hey @roockiee,

which operating system are you on?

**Comment by roockiee** [comment]
Ubuntu 20.04

**Comment by kosecki123** [comment]
Created a simple Dockerfile for testing purposes and was not able to reproduce the error, the build process went fine.

```
FROM ubuntu:20.04

RUN apt-get update -yq \
    && apt-get -yq install curl gnupg ca-certificates \
    && curl -L https://deb.nodesource.com/setup_14.x | bash \
    && apt-get update -yq \
    && apt-get install -yq \
        nodejs build-essential git

RUN npm i -g yarn
RUN git clone https://github.com/energywebfoundation/origin.git
RUN cd origin && yarn
```
