### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by adivated** [energywebfoundation/origin#2178]
Suggest adding these to env.sample to help new users:

DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=origin

Also, the readme link on DB config is a 404 for me (might be due to my perms), maybe double check:

https://github.com/energywebfoundation/origin/tree/master/packages/origin-backend-app#development

**Comment by kosecki123** [comment]
Hey @Rjrunner44 good stuff, added in #2179 and #2180
