### ISSUE TITLE
New User Reg (Perhaps an Issue)

### ISSUE THREAD

**Issue by adivated** [energywebfoundation/origin#2185]
A newly registered user is prompted (actually forced) to register a new org on first registration. However, if you register, and then immediately logout/login, you are not (again) forced to register a new org. You can still do so, but it's now out of the thread I think the site expected.

**Comment by adivated** [comment]
site does enforce it later though as clicking on various things results in: 

"Error Only members of active organization can perform this action"

so it's just a suggested improvement perhaps to redirect the newly logged in user back to the org creation page if they don't have one yet.

**Comment by alexworker23** [comment]
Hey @Rjrunner44!
The modal which appears on user's first login was designed this way. 
It gives the user general info about registering an organization and allowing to quickly go there only once. In the following logins user can easily navigate to "Register Organization" in "Organizations" menu tab and proceed with registration. 
Displaying this modal on each login until the user registers/joins organization could be annoying.
