### ISSUE TITLE
Suggestion: Add Dev Auto-Verify Flag

### ISSUE THREAD

**Issue by adivated** [energywebfoundation/origin#2187]
It might be nice to have a "dev" setting in .env which auto-validates both user registrations and org registrations (just force approve status if flag set in the db). This could just help a bit for devs. Just a thought. There's a risk to this being set in production sites though of course, if it is added. A check if in dev mode on app launch would probably be warranted so the flag isn't left active by accident if it's added.

**Comment by kosecki123** [comment]
We tackled that by creating a dedicated user onboarding documentation

https://energy-web-foundation-origin.readthedocs-hosted.com/en/latest/user-guide-onboarding/
