### ISSUE TITLE
Org Approve UI Issue

### ISSUE THREAD

**Issue by adivated** [energywebfoundation/origin#2189]
on Mac Chrome, the approve for a submitted org is "up a line" (not on the proper org line) Will try to capture a screenshot...

**Comment by adivated** [comment]
<img width="2267" alt="Screen Shot 2021-03-17 at 1 33 45 PM" src="https://user-images.githubusercontent.com/46289259/111534649-75832200-8725-11eb-969b-5489cacaa672.png">

You can't actually click on the "Approve" button. it's up on the prior org in the list line (and it also disappears when you move the mouse to click on it). You have to click the check circle, and the approve does go successfully.

The issue is just usability: it looks to the first time user that they will be approving the prior org in the list (instead of the one they clicked on)...

Trying to approve the first item in the list is also a bit odd. You can't move up to it from lower items, as it never gets it's own approve circle (the one from the line below obscures it and mouse over isn't firing...you have to mouse up away from the top first item, then back down)...

**Comment by josipbagaric** [comment]
It shows up on the line above because it's a kind of a roll-up (opposite of dropdown?) menu.
Tagging @alexworker23 to give his input on the usability.

**Comment by alexworker23** [comment]
This is a default behaviour for all the Table actions throughout Origin. 
The user is supposed to click on the icon of the action in order to perform it.
If you are targeting the check icon - there is no problem of blurring event.
