### ISSUE TITLE
UI not localizing org users table

### ISSUE THREAD

**Issue by adivated** [energywebfoundation/origin#2226]
Most of the UI is using string lookups to localize output, but in the OrganizationUsersTable.tsx there are some hard-code strings for the table headers:

    const columns = [
        { id: 'firstName', label: 'First name' },
        { id: 'lastName', label: 'Last name' },
        { id: 'email', label: 'Email' },
        { id: 'role', label: 'Role' }
    ];

**Comment by josipbagaric** [comment]
Thanks @Rjrunner44. We used to have a non-localized UI - but when we switched to a localized UI, we were too understaffed to do a mass localization, so we decided that we would localize as we go (as-we-code).

I.e. Whenever we change a file, if something is not yet localized - we localize it only then.

Thanks for submitting the issue though, helps us keep track 👌 .

**Comment by josipbagaric** [comment]
Feel free to create an issue for any other missing localizations you encounter.
