### ISSUE TITLE
"start-all" script not defined in "@energyweb/origin-ui" package

### ISSUE THREAD

**Issue by ChangoBuitrago** [energywebfoundation/origin#549]
When running the script `"run:origin"`:
```
"run:origin": "lerna run start-all --scope @energyweb/origin-ui --scope @energyweb/migrations --parallel".
```
origin-ui does not get initialized because `"start-all"` script is undefined for the origin-ui package. However, it works perfectly if it's run manually afterwards through `"run:ui"` that initializes the `"start"` script for the origin-ui package.

**Comment by josipbagaric** [comment]
@ChangoBuitrago thanks for reporting.

Should be fixed now.

**Comment by ChangoBuitrago** [comment]
Works like a charm. Elegant solution. Congrats!
