### ISSUE TITLE
Not optimal balance check.

### ISSUE THREAD

**Issue by kosecki123** [energywebfoundation/origin#730]
Current implementation for getting balance per user is unnecessarily complex.

https://github.com/energywebfoundation/origin/blob/37274aaeb9d881e8759c2121d3c9b80cbda586dd/packages/issuer/src/blockchain-facade/Certificate.ts#L373

Instead of this the better option would be:

- scan for transfers and batch transfers with your address
- take id from those events
- use 1155.balanceOfBatch to resolve balances

Same possibly can be applied to getting claimed balance.

**Comment by josipbagaric** [comment]
This function tries to get **all the owners** for a **specific certificate**, and then based on that calculate the total `energy` value of the certificate and specific ownership per user.

@kosecki123 As far as I can understand, what you describe would give us **all the certificates and balances** for a **specific owner**. Did I understand something wrong?

**Comment by kosecki123** [comment]
Is this functionality still available? @JosephBagaric
