### ISSUE TITLE
Migrate all UI strings to localization package

### ISSUE THREAD

**Issue by e00dan** [energywebfoundation/origin#767]
Strings used in origin-ui-core should be migrated to localization package to allow for full localization of the Origin project.

**Comment by magnus513** [comment]
Hi, Sure I can fix this migration. Can you add me to the repo for pushing a feature-branch?

**Comment by josipbagaric** [comment]
@magnus513 Thanks for the comment. Feel free to fork the repo and open a PR from your fork.
