### ISSUE TITLE
Generation time in Order and Asset tables in Postgre are always generated as current date

### ISSUE THREAD

**Issue by cyn-p** [energywebfoundation/origin#856]
**Reproduce steps:**
1. Request for certificate with Generation time 1st - 30th Apr 2020.
2. After certificate is created, do publish for sale.
<img width="1065" alt="Screen Shot 2563-04-16 at 16 18 34" src="https://user-images.githubusercontent.com/62415190/79440313-09250d80-8000-11ea-8da7-62439f18385e.png">

**Result**
- In Asset, the generationFrom and generationTo are 16th Apr (current date)
<img width="1268" alt="Screen Shot 2563-04-16 at 16 20 31" src="https://user-images.githubusercontent.com/62415190/79440362-19d58380-8000-11ea-8d10-981ed252e7c2.png">

- In Order, the product has the generationFrom and generationTo as 15th Apr
<img width="1408" alt="Screen Shot 2563-04-16 at 16 22 30" src="https://user-images.githubusercontent.com/62415190/79440730-8c466380-8000-11ea-85f1-d057ee901ee5.png">

**Expected**
- Should the generationTime in Asset and Order be the same as the generationTime in the certificate?

**Comment by kosecki123** [comment]
Yes this is correct observation, Asset and Order should have the same Generation To and From as the on-chain Certificate.
